"""Catalog of every topic taught on the site. Shared by home and the All Topics page."""

from __future__ import annotations

TOPICS: list[dict[str, str]] = [
    # Python
    {"area": "Python", "topic": "Scalar types", "what": "int, float, str, bool, None — missing lab is None, not 0", "where": "Python → Types"},
    {"area": "Python", "topic": "Collections", "what": "list, tuple, set, dict; set algebra ∩ ∪ −; tuple as an immutable key", "where": "Python → Collections"},
    {"area": "Python", "topic": "Strings & numbers", "what": "f-strings, slicing, slugs, // vs /, %, round", "where": "Python → Strings & numbers"},
    {"area": "Python", "topic": "Control flow", "what": "if / elif / else, for, while, in", "where": "Python → Control flow"},
    {"area": "Python", "topic": "Functions", "what": "defaults, *args, **kwargs, return, lambda sort key", "where": "Python → Functions"},
    {"area": "Python", "topic": "Comprehensions", "what": "list/dict comps, zip, enumerate, unpacking first, *rest, last", "where": "Python → Comprehensions"},
    {"area": "Python", "topic": "OOP", "what": "class, @dataclass, field(default_factory), @property, methods, __len__", "where": "Python → OOP"},
    {"area": "Python", "topic": "Exceptions", "what": "raise, try / except ValueError, explicit fallbacks", "where": "Python → Exceptions & files"},
    {"area": "Python", "topic": "Files & JSON", "what": "json.dumps / loads, pathlib.Path, CSV export", "where": "Python → Exceptions & files"},
    {"area": "Python", "topic": "Datetime", "what": "datetime, timedelta, weekday, ISO; Pandas .dt", "where": "Python → Datetime"},
    {"area": "Python", "topic": "collections", "what": "Counter, defaultdict, namedtuple, deque(maxlen)", "where": "Python → Stdlib"},
    {"area": "Python", "topic": "Generators", "what": "yield, one-pass streams, itertools.islice", "where": "Python → Generators & itertools"},
    {"area": "Python", "topic": "itertools", "what": "product (OneHot-style crosses), groupby", "where": "Python → Generators & itertools"},
    {"area": "Python", "topic": "Typing", "what": "Literal, Callable, annotations (not runtime checks)", "where": "Python → Typing & decorators"},
    {"area": "Python", "topic": "Decorators", "what": "@wraps, call counters — same idea as tool wrappers", "where": "Python → Typing & decorators"},
    {"area": "Python", "topic": "Context managers", "what": "with, @contextmanager (isolation / resources)", "where": "Python → Typing & decorators"},
    # NumPy
    {"area": "NumPy", "topic": "ndarray shape / dtype", "what": "lab_means (8×14), protocol (8×14), inventory (5×14), cost (14,)", "where": "NumPy labs"},
    {"area": "NumPy", "topic": "matmul / @", "what": "panel_cost = protocol @ assay_cost; pull = counts @ protocol", "where": "NumPy labs · Capstone reagents"},
    {"area": "NumPy", "topic": "Broadcasting", "what": "patient vector vs ref_low/ref_high; z vs band", "where": "NumPy labs"},
    {"area": "NumPy", "topic": "Boolean masks", "what": "abnormal = (x < low) | (x > high); reagent reorder mask", "where": "NumPy labs · flag_labs"},
    {"area": "NumPy", "topic": "Fancy / integer index", "what": "bincount + matmul vs Python loop over conditions", "where": "NumPy labs"},
    {"area": "NumPy", "topic": "View vs copy", "what": "slicing can mutate the atlas; .copy() before write", "where": "NumPy labs"},
    {"area": "NumPy", "topic": "Axis reductions", "what": "mean(axis=0) by assay; sum(axis=1) by site", "where": "NumPy labs"},
    {"area": "NumPy", "topic": "clip / nan", "what": "clip labs to physiologic ranges; missing lactate/troponin as nan", "where": "clinic/data.py · flag_labs"},
    {"area": "NumPy", "topic": "L2 nearest prototype", "what": "argmin ||lab_means - x|| → nearest_condition", "where": "Agent"},
    # Pandas
    {"area": "Pandas", "topic": "DataFrame / Series", "what": "encounters ledger, dtypes, memory, head", "where": "Pandas chart"},
    {"area": "Pandas", "topic": "loc / boolean filter", "what": "site, arrival, ESI masks; hypoxia spo2 < 92", "where": "Pandas chart"},
    {"area": "Pandas", "topic": "groupby agg", "what": "n, admit_rate, avg_wait by site × condition", "where": "Pandas chart"},
    {"area": "Pandas", "topic": "transform", "what": "wait / site_mean aligned to original index", "where": "Pandas chart"},
    {"area": "Pandas", "topic": "merge", "what": "encounters ⨝ patients on patient_id (left join)", "where": "Pandas chart"},
    {"area": "Pandas", "topic": "Missing data", "what": "dropna vs site median vs site+ESI median (lactate/troponin)", "where": "Pandas chart"},
    {"area": "Pandas", "topic": "Time series", "what": "shift(7), rolling(7), .dt hour/dow", "where": "Pandas chart"},
    {"area": "Pandas", "topic": "crosstab / pivot", "what": "site × condition counts", "where": "Pandas chart"},
    {"area": "Pandas", "topic": "Categorical", "what": "site, arrival, season, ordered ESI; observed=True", "where": "clinic/data.py"},
    # EDA
    {"area": "EDA", "topic": "Line / bar / box", "what": "census over time; hour × arrival; wait vs ESI × season", "where": "EDA & charts"},
    {"area": "EDA", "topic": "Heatmap", "what": "admit rate site × hour", "where": "EDA & charts"},
    {"area": "EDA", "topic": "Scatter", "what": "volume vs admit rate; wait vs SpO2", "where": "EDA & charts"},
    {"area": "EDA", "topic": "Correlation", "what": "Pearson on site-day numerics; Simpson warning", "where": "EDA & charts"},
    {"area": "EDA", "topic": "Plotly + seaborn", "what": "interactive Plotly; seaborn scatter sample", "where": "EDA & charts"},
    # Features
    {"area": "Features", "topic": "Calendar features", "what": "dow, is_weekend, flu_wave, is_heat", "where": "Feature engineering"},
    {"area": "Features", "topic": "Lag / roll", "what": "enc_lag7, enc_roll7 = shift(1).rolling(7) per site", "where": "Feature engineering"},
    {"area": "Features", "topic": "Time split vs random", "what": "same model, two splits; random inflates R²", "where": "Feature engineering"},
    {"area": "Features", "topic": "Leakage", "what": "same-day admit_rate as a feature; encoder fit on full frame", "where": "Feature engineering"},
    {"area": "Features", "topic": "Target encoding leak", "what": "mean admit by condition on the full table", "where": "Feature engineering"},
    {"area": "Features", "topic": "High-cardinality IDs", "what": "do not one-hot patient_id / MRN", "where": "Feature engineering"},
    # Regression
    {"area": "Regression", "topic": "Problem", "what": "predict site-day encounter census", "where": "Regression"},
    {"area": "Regression", "topic": "Naive baseline", "what": "lag-7; beat it or you have no model", "where": "Regression"},
    {"area": "Regression", "topic": "Linear / Ridge / RF", "what": "estimators behind the same Pipeline", "where": "Regression"},
    {"area": "Regression", "topic": "MAE RMSE R²", "what": "metrics on the time-split test window", "where": "Regression"},
    {"area": "Regression", "topic": "Residuals", "what": "residual vs predicted, colored by site", "where": "Regression"},
    {"area": "Regression", "topic": "Coefficients / importance", "what": "linear coefs after scaling; RF impurity importance (debug only)", "where": "Regression"},
    # Classification
    {"area": "Classification", "topic": "Problem", "what": "P(admit) at encounter level", "where": "Classification"},
    {"area": "Classification", "topic": "Class imbalance", "what": "majority discharge; dummy accuracy is a trap", "where": "Classification"},
    {"area": "Classification", "topic": "LogReg / RandomForest", "what": "class_weight none vs balanced", "where": "Classification"},
    {"area": "Classification", "topic": "Threshold", "what": "cut on P(admit); bed budget, not 0.5", "where": "Classification · Agent"},
    {"area": "Classification", "topic": "Confusion matrix", "what": "discharge vs admit, labeled table of precision/recall/F1", "where": "Classification"},
    {"area": "Classification", "topic": "ROC and PR", "what": "AUC; precision–recall for the minority class", "where": "Classification"},
    {"area": "Classification", "topic": "Imputation in Pipeline", "what": "SimpleImputer median on train only (lactate, troponin)", "where": "clinic/ml.py"},
    # Clusters / pipelines
    {"area": "Clusters & pipelines", "topic": "K-means", "what": "k groups on scaled patient features; k is a choice", "where": "Clusters"},
    {"area": "Clusters & pipelines", "topic": "Scaling", "what": "StandardScaler so age does not drown comorbid", "where": "Clusters"},
    {"area": "Clusters & pipelines", "topic": "PCA", "what": "2D view of segments (visualization, not a diagnosis)", "where": "Clusters"},
    {"area": "Clusters & pipelines", "topic": "Silhouette", "what": "tightness hint; name the cluster in English", "where": "Clusters"},
    {"area": "Clusters & pipelines", "topic": "Phenotypes", "what": "unsupervised segments (older high-util, …)", "where": "Clusters · Capstone"},
    {"area": "Clusters & pipelines", "topic": "Pipeline", "what": "ColumnTransformer + estimator; one object to dump", "where": "Clusters"},
    {"area": "Clusters & pipelines", "topic": "TimeSeriesSplit + GridSearch", "what": "walk-forward α grid; no shuffled Fridays", "where": "Clusters"},
    # Agent
    {"area": "Agent", "topic": "Tool", "what": "named callable: get_chart, flag_labs, score_admit, nearest_condition, retrieve_protocol", "where": "Agent workflow"},
    {"area": "Agent", "topic": "Planner", "what": "deterministic plan(state); swap for LLM {tool, args} later", "where": "Agent workflow"},
    {"area": "Agent", "topic": "State / memory", "what": "chart, lab_flags, admit_score, protocol, red_flags", "where": "clinic/agent.py"},
    {"area": "Agent", "topic": "Trace", "what": "thought → tool → observation audit log", "where": "Agent workflow"},
    {"area": "Agent", "topic": "Stop + recommend", "what": "suggested plan for a clinician; not a diagnosis", "where": "Agent workflow"},
    {"area": "Agent", "topic": "Gold labels", "what": "hidden from planner; eval only (no RAG leakage)", "where": "Agent workflow"},
    {"area": "Agent", "topic": "Model as a tool", "what": "sklearn Pipeline is score_admit, not the product", "where": "Agent · Capstone"},
    # Capstone
    {"area": "Capstone", "topic": "Census board", "what": "forecast vs actual vs lag-7; season what-if", "where": "Capstone"},
    {"area": "Capstone", "topic": "Reagent pull", "what": "counts @ protocol vs on-hand cover", "where": "Capstone"},
    {"area": "Capstone", "topic": "Admit desk", "what": "score a live ticket (ESI, SpO2, arrival, …)", "where": "Capstone"},
    {"area": "Capstone", "topic": "Run agent", "what": "same loop on tonight’s board", "where": "Capstone"},
]
